require'nvim-treesitter.configs'.setup({
  ensure_installed = {
    "c",
    "scala",
    "json",
    "python",
    "yaml",
    "markdown",
    "bash",
    "vim",
    "dockerfile",
    -- "gitignore",
    -- "diff",
    -- "git_rebase",
    -- "gitcommit",
    -- "gitattributes",
    -- "git_config",
  },
  sync_install = true,
  auto_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = { enable = true },
  -- autotag = { enable = true },
})
