require'nvim-treesitter.configs'.setup({
  ensure_installed = {
    "c",
    "scala",
    "json",
    "python",
    "yaml",
    "markdown",
    "bash",
    "vim",
    "dockerfile",
    "gitignore",
    "diff",
    "git_rebase",
    "gitcommit",
    "gitattributes",
    "git_config",
  },
  sync_install = true,
  auto_install = true,
  highlight = {
    enable = true,
  },
  -- indent = { enable = true },
  -- autotag = { enable = true },
})
