[tools]
poetry = "latest"
python = "3.12"
neovim  = "0.10.3"
nodejs = "23.5.0"
golang = "1.23.4"
java = "zulu-8.80.0.17"
saml2aws = "2.36.18"
kubectl = "1.32.0"
helm = "3.16.4"
ruby = "2.7.8"
k9s = "0.32.7"
direnv = "2.35.0"
vault = "1.18.3"
ripgrep = "14.1.1"
fzf = "0.57.0"
terraform = "1.10.3"
bat = "0.24.0"
awscli = "latest"
